### ISSUE TITLE
Compiler errors with zig v0.8.0

### ISSUE THREAD

**Issue by postspectacular** [msinilo/zigtracer#1]
Hey, just out of interest, which version of zig did you build this with/for? It seems there have been quite a few breaking API changes to `std.Thread` and the project doesn't compile anymore with zig v0.8.0. I could fix some easy ones (e.g. `Thread.getCpuCount()` now `Thread.cpuCount()`), but the whole `Futex` stuff has disappeared/restructured in the latest stdlib and any guidance would be highly appreciated...

**Comment by msinilo** [comment]
I am on a fairly recent nightly build - 0.9.0-dev.473+9979741bf . I did notice some diffs when comparing code using Godbolt, but I assumed it'd eventually be 'promoted' to stable

**Comment by msinilo** [comment]
Yeah, I tried it with compiler explorer and trunk (latest) compiles fine, 0.8.0 does not, but I'd argue it's not super valuable to try and make it run with an older version
